//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Курсовая.NET_Framework__WinForms_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribers
    {
        public int Id { get; set; }
        public int PBXId { get; set; }
        public string Extension { get; set; }
        public string Port { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int PhoneId { get; set; }
        public string AddInfo { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual PBX PBX { get; set; }
        public virtual Phones Phones { get; set; }
    }
}
